name: Carter M. Young
description: Owner’s Representative for Construction Projects
url: https://www.cartermyoung.com

#
# Don't change any of the following
#

# Jekyll Now version
version: v1.2.0

# Jekyll 3 only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM

# Set the Sass partials directory using @imports
# sass:
#  style: :compressed

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
